### ISSUE TITLE
vpn unlimited errors

### ISSUE THREAD

**Issue by brauliobo** [troyengel/archbuild#2]
updated version to 2.8.0, build and tried running `vpnu-arch`:
```
vpn-unlimited: /usr/lib/libcurl.so.3: no version information available (required by /usr/lib/libvpnu_rpc.so.1)
vpn-unlimited: /usr/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/libvpnu_enc.so.1)
vpn-unlimited: symbol lookup error: /usr/lib/libvpnu_rpc.so.1: undefined symbol: _ZNK4Json5Value8asStringEv
```

**Comment by troyengel** [comment]
These PKGBUILD files are deprecated since AUR moved to 4.0 with full git support, this specific package was a one-off for a user in the forums and the software never really worked right, so nobody picked it up. Feel free to upload and maintain this on the new AUR.
